items = {
    -- Head
    ["Cowl of Light's Purity"] = {rank = 1, phase = 5, value = 282.95},
    ["Cowl of Absolution"] = {rank = 2, phase = 3, value = 239},
    ["Cowl of the Avatar"] = {rank = 3, phase = 2, value = 223},
    ["Cowl of Benevolence"] = {rank = 4, phase = 3, value = 219.95},
    ["Light-Collar of the Incarnate"] = {rank = 5, phase = 1, value = 190.5},
    ["Hood of the Third Eye"] = {rank = 6, phase = 4, value = 179.5},
    ["Mojo Mender's Mask"] = {rank = 7, phase = 4, value = 175},
    ["Crown of the Sun"] = {rank = 8, phase = 2, value = 167.75},
    ["Whitemend Hood"] = {rank = 9, phase = 1, value = 160.85},
    ["Cowl of Naaru Blessings"] = {rank = 10, phase = 1, value = 160.4},
    ["Brutal Gladiator's Mooncloth Hood"] = {rank = 11, phase = 5, value = 151.9},
    ["Hallowed Crown"] = {rank = 12, phase = 1, value = 148.2},
    ["Powerheal 4000 Lens"] = {rank = 13, phase = 1, value = 144.35},
    ["Vengeful Gladiator's Mooncloth Hood"] = {rank = 14, phase = 4, value = 133.05},
    ["Headdress of the High Potentate"] = {rank = 15, phase = 1, value = 129.05},
    ["Merciless Gladiator's Mooncloth Hood"] = {rank = 16, phase = 3, value = 119.9},
    ["Gladiator's Mooncloth Hood"] = {rank = 17, phase = 1, value = 119.6},
    ["Circlet of Faith"] = {rank = 18, phase = 0, value = 115.7},
    ["Scintillating Headdress of Second Sight"] = {rank = 19, phase = 1, value = 113.2},
    ["Watcher's Cowl"] = {rank = 20, phase = 1, value = 107.05},
    ["Collar of Command"] = {rank = 21, phase = 1, value = 101.3},
    ["Halo of Transcendence"] = {rank = 22, phase = 0, value = 99.52},
    ["Ouro"] = {rank = 23, phase = 0, value = 98.8},
    ["Azuregos"] = {rank = 24, phase = 0, value = 97.8},
    ["Evoker's Helmet of Second Sight"] = {rank = 25, phase = 1, value = 92.68},
    ["Ghostly Headwrap"] = {rank = 26, phase = 1, value = 62.4},
    -- Neck
    ["Brooch of Nature's Mercy"] = {rank = 1, phase = 4, value = 137.8},
    ["Brooch of the Highborne"] = {rank = 2, phase = 5, value = 121.75},
    ["Lord Sanguinnar's Claim"] = {rank = 3, phase = 2, value = 101.65},
    ["Nadina's Pendant of Purity"] = {rank = 4, phase = 3, value = 100.01},
    ["Teeth of Gruul"] = {rank = 5, phase = 1, value = 92.6},
    ["Embersput Talisman"] = {rank = 6, phase = 1, value = 80.3},
    ["Archaic Charm of Presence"] = {rank = 7, phase = 1, value = 78.4},
    ["Shining Chain of the Afterworld"] = {rank = 8, phase = 1, value = 73.5},
    ["Gezzarak's Fang"] = {rank = 9, phase = 1, value = 67.6},
    ["Natasha's Guardian Chord"] = {rank = 10, phase = 1, value = 67},
    ["Necklace of Eternal Hope"] = {rank = 11, phase = 1, value = 66.3},
    ["Karja's Medallion"] = {rank = 12, phase = 1, value = 66},
    ["Necklace of Resplendent Hope"] = {rank = 13, phase = 1, value = 64.9},
    ["Swampstone Necklace"] = {rank = 14, phase = 1, value = 62.7},
    ["Necklace of Necropsy"] = {rank = 15, phase = 0, value = 61.7},
    ["Amulet of the Fallen God"] = {rank = 16, phase = 0, value = 61.15},
    ["Choker of Fluid Thought"] = {rank = 17, phase = 1, value = 59.35},
    ["Pendant of Dominance"] = {rank = 18, phase = 1, value = 45.6},
    ["Talisman of the Breaker"] = {rank = 19, phase = 1, value = 31.3},
    -- Shoulders
    ["Shawl of Wonderment"] = {rank = 1, phase = 5, value = 192.85},
    ["Mantle of the Avatar"] = {rank = 2, phase = 2, value = 143.7},
    ["Swiftheal Mantle"] = {rank = 3, phase = 3, value = 141.45},
    ["Mantle of Absolution"] = {rank = 4, phase = 3, value = 138.3},
    ["Amice of Brilliant Light"] = {rank = 5, phase = 3, value = 127.7},
    ["Primal Mooncloth Shoulders"] = {rank = 6, phase = 1, value = 121.37},
    ["Light-Mantle of the Incarnate"] = {rank = 7, phase = 1, value = 116.15},
    ["Pauldrons of the Solace Giver"] = {rank = 8, phase = 1, value = 115},
    ["Brutal Gladiator's Mooncloth Mantle"] = {rank = 9, phase = 5, value = 102},
    ["Hallowed Paulders"] = {rank = 10, phase = 1, value = 96.7},
    ["Vengeful Gladiator's Mooncloth Mantle"] = {rank = 11, phase = 4, value = 88.85},
    ["Shoulderpads of Faith"] = {rank = 12, phase = 0, value = 83.05},
    ["Pauldrons of Sufferance"] = {rank = 13, phase = 1, value = 80.1},
    ["Vestia's Pauldrons of Inner Grace"] = {rank = 14, phase = 1, value = 79.6},
    ["Merciless Gladiator's Mooncloth Mantle"] = {rank = 15, phase = 3, value = 78.95},
    ["Gladiator's Mooncloth Mantle"] = {rank = 16, phase = 1, value = 77.2},
    ["Shoulders of Transcendence"] = {rank = 17, phase = 0, value = 71.07},
    ["Ternary Mantle"] = {rank = 18, phase = 0, value = 69.4},
    -- Back
    ["Shroud of the Highborne"] = {rank = 1, phase = 3, value = 112.4},
    ["Shroud of Redeemed Souls"] = {rank = 2, phase = 5, value = 111.45},
    ["Sunshower Light Cloak"] = {rank = 3, phase = 2, value = 101.7},
    ["Wristbands of Divine Influence"] = {rank = 4, phase = 3, value = 99.75},
    ["Cloak of Ancient Rituals"] = {rank = 5, phase = 4, value = 89.4},
    ["Stainless Cloak of the Pure Hearted"] = {rank = 6, phase = 1, value = 79.4},
    ["Red Riding Hood's Cloak"] = {rank = 7, phase = 1, value = 74.3},
    ["Livegiving Cloak"] = {rank = 8, phase = 1, value = 74.1},
    ["Cloak of Swift Reprieve"] = {rank = 9, phase = 5, value = 73.7},
    ["Avian Cloak of Feathers"] = {rank = 10, phase = 1, value = 72.5},
    ["Cloak of Suturing"] = {rank = 11, phase = 0, value = 72.5},
    ["Shadowcaster's Drape"] = {rank = 12, phase = 4, value = 70.2},
    ["Kharmaa's Shroud of Hope"] = {rank = 13, phase = 4, value = 69.5},
    ["Cloak of Clarity"] = {rank = 14, phase = 0, value = 68.9},
    ["Bishop's Cloak"] = {rank = 15, phase = 1, value = 67.95},
    ["Shadowvine Cloak of Infusion"] = {rank = 16, phase = 1, value = 67.3},
    ["Cloak of Scintillating Auras"] = {rank = 17, phase = 1, value = 65},
    ["Cloak of the Everliving"] = {rank = 18, phase = 1, value = 64.9},
    ["White Remedy Cape"] = {rank = 19, phase = 1, value = 64.7},
    ["Apexis Cloak"] = {rank = 20, phase = 1, value = 58.35},
    ["Light-Touched Stole of Altruism"] = {rank = 21, phase = 1, value = 57.85},
    ["Cloak of Whispering Shells"] = {rank = 22, phase = 1, value = 55.55},
    -- Chest
    ["Robes of Faltered Light"] = {rank = 1, phase = 5, value = 257.55},
    ["Vestments of Absolution"] = {rank = 2, phase = 3, value = 223.8},
    ["Vestments of the Avatar"] = {rank = 3, phase = 2, value = 194.4},
    ["Gown of Spiritual Wonder"] = {rank = 4, phase = 5, value = 190.6},
    ["Robes of Heavenly Purpose"] = {rank = 5, phase = 4, value = 186.45},
    ["Primal Mooncloth Robe"] = {rank = 6, phase = 1, value = 175.27},
    ["Wristbands of Divine Influence"] = {rank = 7, phase = 3, value = 174.15},
    ["Robes of the Incarnate"] = {rank = 8, phase = 1, value = 162.5},
    ["Brutal Gladiator's Mooncloth Robe"] = {rank = 9, phase = 5, value = 149.3},
    ["Hallowed Garments"] = {rank = 10, phase = 1, value = 129.5},
    ["Vengeful Gladiator's Mooncloth Robe"] = {rank = 11, phase = 4, value = 127.95},
    ["Robe of Effervescent Light"] = {rank = 12, phase = 1, value = 121.55},
    ["Masquerade Gown"] = {rank = 13, phase = 1, value = 119.45},
    ["Merciless Gladiator's Mooncloth Robe"] = {rank = 14, phase = 3, value = 118.05},
    ["Gladiator's Mooncloth Robe"] = {rank = 15, phase = 1, value = 110.35},
    ["Robes of Faith"] = {rank = 16, phase = 0, value = 110.1},
    ["Robes of Transcendence"] = {rank = 17, phase = 0, value = 100.72},
    ["Watcher's Tunic"] = {rank = 18, phase = 1, value = 86.65},
    -- Wrist
    ["Cuffs of Absolution"] = {rank = 1, phase = 5, value = 139.35},
    ["Bracers of Martyrdom"] = {rank = 2, phase = 3, value = 108.15},
    ["Wristbands of Divine Influence"] = {rank = 3, phase = 3, value = 95.6},
    ["Wristguards of Tranquil Thought"] = {rank = 4, phase = 4, value = 88.11},
    ["Wraps of Purification"] = {rank = 5, phase = 2, value = 81.1},
    ["Bands of Indwelling"] = {rank = 6, phase = 1, value = 72.3},
    ["Bindings of Transcendence"] = {rank = 7, phase = 0, value = 69.92},
    ["Bands of the Benevolent"] = {rank = 8, phase = 1, value = 66.35},
    ["Bindings of Faith"] = {rank = 9, phase = 0, value = 64.05},
    ["Veteran's Mooncloth Cuffs"] = {rank = 10, phase = 5, value = 60.75},
    ["Bracelets of Royal Redemption"] = {rank = 11, phase = 1, value = 59.8},
    ["Bindings of the Timewalker"] = {rank = 12, phase = 1, value = 59.5},
    ["Light Scribe Bands"] = {rank = 13, phase = 1, value = 57.8},
    ["Goldenvine Wraps"] = {rank = 14, phase = 1, value = 47.55},
    ["Shattrath Wraps"] = {rank = 15, phase = 1, value = 44.1},
    ["Bracers of Havok"] = {rank = 16, phase = 1, value = 43.2},
    -- Hands
    ["Handguards of the Dawn"] = {rank = 1, phase = 5, value = 195.15},
    ["Gloves of Absolution"] = {rank = 2, phase = 3, value = 154.75},
    ["Gloves of the Avatar"] = {rank = 3, phase = 2, value = 138.5},
    ["Light Blessed Bonds"] = {rank = 4, phase = 4, value = 131.05},
    ["Handwraps of the Incarnate"] = {rank = 5, phase = 1, value = 113.8},
    ["Gloves of Saintly Blessings"] = {rank = 6, phase = 1, value = 110.55},
    ["Brutal Gladiator's Mooncloth Gloves"] = {rank = 7, phase = 5, value = 86.8},
    ["Hallowed Handwraps"] = {rank = 8, phase = 1, value = 83.75},
    ["Prismatic Mittens of Mending"] = {rank = 9, phase = 1, value = 83.45},
    ["Bloody Surgeon's Mitts"] = {rank = 10, phase = 1, value = 82.9},
    ["Gloves of Faith"] = {rank = 11, phase = 1, value = 81.6},
    ["Vengeful Gladiator's Mooncloth Gloves"] = {rank = 12, phase = 4, value = 73.65},
    ["Gloves of Transcendence"] = {rank = 13, phase = 1, value = 73.02},
    ["Gloves of Piety"] = {rank = 14, phase = 1, value = 72.6},
    ["Gloves of Penitence"] = {rank = 15, phase = 1, value = 71.7},
    ["Merciless Gladiator's Mooncloth Gloves"] = {rank = 16, phase = 3, value = 63.75},
    ["Gladiator's Mooncloth Gloves"] = {rank = 17, phase = 1, value = 60.4},
    ["Messiah"] = {rank = 18, phase = 1, value = 60.05},
    ["Desert Bloom Gloves"] = {rank = 19, phase = 1, value = 50.05},
    -- Waist
    ["Belt of Absolution"] = {rank = 1, phase = 5, value = 190.45},
    ["Belt of Divine Guidance"] = {rank = 2, phase = 3, value = 138.75},
    ["Angelista's Sash"] = {rank = 3, phase = 3, value = 137.05},
    ["Belt of the Long Road"] = {rank = 4, phase = 2, value = 133.85},
    ["Primal Mooncloth Belt"] = {rank = 5, phase = 1, value = 132.07},
    ["Cord of Braided Troll Hair"] = {rank = 6, phase = 4, value = 130.55},
    ["Belt of Divine Inspiration"] = {rank = 7, phase = 1, value = 109.95},
    ["Cincture of Will"] = {rank = 8, phase = 1, value = 95.8},
    ["Cord of Belief"] = {rank = 9, phase = 1, value = 95.2},
    ["Black Belt of Knowledge"] = {rank = 10, phase = 1, value = 87.9},
    ["Cord of Sanctification"] = {rank = 11, phase = 1, value = 81.8},
    ["Veteran's Mooncloth Belt"] = {rank = 12, phase = 5, value = 80.65},
    ["Grasp of the Old God"] = {rank = 13, phase = 1, value = 80.65},
    ["Lifeblood Belt"] = {rank = 14, phase = 1, value = 78.6},
    ["Belt of Faith"] = {rank = 15, phase = 0, value = 77.2},
    ["Belt of Transcendence"] = {rank = 16, phase = 0, value = 67.97},
    -- Legs
    ["Pants of Calming Strife"] = {rank = 1, phase = 5, value = 225.98},
    ["Leggings of Eternity"] = {rank = 2, phase = 3, value = 213.25},
    ["Gilded Trousers of Benediction"] = {rank = 3, phase = 1, value = 210.15},
    ["Breeches of Absolution"] = {rank = 4, phase = 3, value = 193.9},
    ["Breeches of the Avatar"] = {rank = 5, phase = 2, value = 193.85},
    ["Adorned Supernal Legwraps"] = {rank = 6, phase = 5, value = 193.35},
    ["Trousers of the Incarnate"] = {rank = 7, phase = 1, value = 183.75},
    ["Achromic Trousers of the Naaru"] = {rank = 8, phase = 4, value = 156.5},
    ["Star-Soul Breeches"] = {rank = 9, phase = 2, value = 155.75},
    ["Whitemend Pants"] = {rank = 10, phase = 1, value = 152.35},
    ["Pantaloons of Repentance"] = {rank = 11, phase = 1, value = 151.75},
    ["Brutal Gladiator's Mooncloth Gloves"] = {rank = 12, phase = 5, value = 147.05},
    ["Pontifex Kilt"] = {rank = 13, phase = 1, value = 137.3},
    ["Kamaei's Cerulean Skirt"] = {rank = 14, phase = 1, value = 135.4},
    ["Pontiff's Pantaloons of Prophecy"] = {rank = 15, phase = 1, value = 129.3},
    ["Vengeful Gladiator's Mooncloth Gloves"] = {rank = 16, phase = 4, value = 125.7},
    ["Hallowed Trousers"] = {rank = 17, phase = 1, value = 121.55},
    ["Leggings of Transcendence"] = {rank = 18, phase = 0, value = 109.57},
    ["Merciless Gladiator's Mooncloth Gloves"] = {rank = 19, phase = 3, value = 107.55},
    ["Pants of the Naaru"] = {rank = 20, phase = 1, value = 105.55},
    ["Leggings of Faith"] = {rank = 21, phase = 0, value = 105.35},
    ["Gladiator's Mooncloth Leggings"] = {rank = 22, phase = 1, value = 104.1},
    ["Empowered Leggings"] = {rank = 23, phase = 0, value = 99.35},
    -- Feet
    ["Boots of Absolution"] = {rank = 1, phase = 5, value = 190.95},
    ["Slippers of Dutiful Mending"] = {rank = 2, phase = 5, value = 140.6},
    ["Two-toed Sandals"] = {rank = 3, phase = 4, value = 133.15},
    ["Soul-Strider Boots"] = {rank = 4, phase = 2, value = 132.6},
    ["Boots of the Divine Light"] = {rank = 5, phase = 3, value = 131.35},
    ["Archbishop's Slippers"] = {rank = 6, phase = 3, value = 129.65},
    ["Boots of the Long Road"] = {rank = 7, phase = 2, value = 124.95},
    ["Boots of the Incorrupt"] = {rank = 8, phase = 1, value = 109},
    ["Boots of the Pious"] = {rank = 9, phase = 1, value = 90.25},
    ["Footpads of Madness"] = {rank = 10, phase = 4, value = 88.85},
    ["Slippers of Serenity"] = {rank = 11, phase = 1, value = 87.7},
    ["Curate's Boots"] = {rank = 12, phase = 1, value = 87.4},
    ["Sandals of Faith"] = {rank = 13, phase = 0, value = 84.25},
    ["Light-Woven Slippers"] = {rank = 14, phase = 1, value = 81.35},
    ["Veteran's Mooncloth Slippers"] = {rank = 15, phase = 5, value = 80.65},
    ["Jeweled Boots of Sanctification"] = {rank = 16, phase = 1, value = 80.1},
    ["Boots of Transcendence"] = {rank = 17, phase = 0, value = 76.12},
    ["Boots of Pure Thought"] = {rank = 18, phase = 0, value = 71.6},
    ["Imbued Netherweave Boots"] = {rank = 19, phase = 1, value = 56.7},
    -- Ring
    ["Band of Lucent Beams"] = {rank = 1, phase = 5, value = 126},
    ["Signet of the Quiet Forest"] = {rank = 2, phase = 4, value = 121.6},
    ["Blessed Band of Karabor"] = {rank = 3, phase = 3, value = 111.4},
    ["Ring of Harmonic Beauty"] = {rank = 4, phase = 5, value = 109.55},
    ["Coral Band of the Revived"] = {rank = 5, phase = 2, value = 99.25},
    ["Anveena's Touch"] = {rank = 6, phase = 5, value = 96.85},
    ["Phoenix Ring of Rebirth"] = {rank = 7, phase = 2, value = 88.2},
    ["Sin'dorei Band of Salvation"] = {rank = 8, phase = 5, value = 85.4},
    ["Naaru Lightwarden's Band"] = {rank = 9, phase = 1, value = 85.05},
    ["Jade Ring of the Everliving"] = {rank = 10, phase = 1, value = 84.4},
    ["Violet Signet of the Grand Restorer"] = {rank = 11, phase = 1, value = 80.6},
    ["Ring of Calming Waves"] = {rank = 12, phase = 3, value = 79.83},
    ["Ring of Faith"] = {rank = 13, phase = 0, value = 75.3},
    ["Mender's Heart Ring"] = {rank = 14, phase = 1, value = 71.9},
    ["Witches Band"] = {rank = 15, phase = 1, value = 69.7},
    ["Signet of Unshakable Faith"] = {rank = 16, phase = 1, value = 69.35},
    ["Ring of Fabled Hope"] = {rank = 17, phase = 1, value = 67.8},
    ["Ring of Convalescence"] = {rank = 18, phase = 1, value = 67.6},
    ["Ancestral Band"] = {rank = 19, phase = 1, value = 67.6},
    ["Band of Halos"] = {rank = 20, phase = 1, value = 66.35},
    ["Ring of Flowing Light"] = {rank = 21, phase = 1, value = 65.83},
    ["Celestial Jewel Ring"] = {rank = 22, phase = 1, value = 64.4},
    ["Spiritualist's Mark of the Sha'tar"] = {rank = 23, phase = 1, value = 63.2},
    ["Cosmic Lifeband"] = {rank = 24, phase = 1, value = 63.1},
    ["Gift of the Talonpriests"] = {rank = 25, phase = 1, value = 62.4},
    ["Band of Unanswered Prayers"] = {rank = 26, phase = 0, value = 62.15},
    ["Band of the Crystalline Void"] = {rank = 27, phase = 1, value = 61.4},
    ["Pure Elementium Band"] = {rank = 28, phase = 0, value = 60.85},
    ["Signet of Repose"] = {rank = 29, phase = 1, value = 56.05},
    ["Ring of Spiritual Precision"] = {rank = 30, phase = 1, value = 47.55},
    -- Tinket
    ["Redeemer's Alchemist's Stone"] = {rank = 1, phase = 5, value = 195.2},
    ["Glimmering Naaru Sliver"] = {rank = 2, phase = 5, value = 153.53},
    ["Alchemist's Stone"] = {rank = 3, phase = 1, value = 127.75},
    ["Memento of Tyrande"] = {rank = 4, phase = 3, value = 122.9},
    ["Essence of the Martyr"] = {rank = 5, phase = 1, value = 110.34},
    ["Earing of Soulful Meditation"] = {rank = 6, phase = 2, value = 110.3},
    ["Tome of Diabolic Remedy"] = {rank = 7, phase = 4, value = 105.72},
    ["Eye of the Dead"] = {rank = 8, phase = 0, value = 97.4},
    ["Fel Reaver's Piston"] = {rank = 9, phase = 2, value = 90},
    ["Ribbon of Sacrifice"] = {rank = 10, phase = 1, value = 87.15},
    ["Figurine - Talasite Owl"] = {rank = 11, phase = 1, value = 86.75},
    ["Lower City Prayerbook"] = {rank = 12, phase = 1, value = 85},
    ["Pendant of the Violet Eye"] = {rank = 13, phase = 1, value = 82.31},
    ["Eye of Gruul"] = {rank = 14, phase = 1, value = 82.2},
    ["Rejuvenating Gem"] = {rank = 15, phase = 0, value = 75.3},
    ["Battlemaster's Perseverance"] = {rank = 16, phase = 4, value = 73.4},
    ["Scarab of the Infinite Cycle"] = {rank = 17, phase = 1, value = 71},
    ["Auslese's Light Channeler"] = {rank = 18, phase = 1, value = 62.13},
    ["Darkmoon Card: Blue Dragon"] = {rank = 19, phase = 0, value = 57.36},
    ["Warp-Scarab Brooch"] = {rank = 20, phase = 1, value = 54.5},
    ["Bangle of Endless Blessings"] = {rank = 21, phase = 1, value = 53.1},
    ["Xi'ri's Gift"] = {rank = 22, phase = 1, value = 29.11},
    ["Vengeance of the Illidari"] = {rank = 23, phase = 1, value = 21.59},
    -- Main Hand
    ["Archon's Gavel"] = {rank = 1, phase = 5, value = 463.1},
    ["Crystal Spire of Karabor"] = {rank = 2, phase = 3, value = 448.9},
    ["Brutal Gladiator's Salvation"] = {rank = 3, phase = 5, value = 421.9},
    ["Lightfathom Scepter"] = {rank = 4, phase = 2, value = 399.3},
    ["Dark Blessing"] = {rank = 5, phase = 4, value = 396},
    ["Gavel of Naaru Blessings"] = {rank = 6, phase = 5, value = 395.7},
    ["Vengeful Gladiator's Salvation"] = {rank = 7, phase = 4, value = 391.35},
    ["Hammer of Atonement"] = {rank = 8, phase = 3, value = 378.58},
    ["Merciless Gladiator's Salvation"] = {rank = 9, phase = 3, value = 356.75},
    ["Light's Justice"] = {rank = 10, phase = 1, value = 343.2},
    ["Gladiator's Salvation"] = {rank = 11, phase = 1, value = 315.8},
    ["Shard of the Virtuous"] = {rank = 12, phase = 1, value = 310.5},
    ["Hand of Eternity"] = {rank = 13, phase = 1, value = 287.1},
    ["The Ancient Scepter of Sue-Min"] = {rank = 14, phase = 1, value = 271.2},
    ["Shockwave Truncheon"] = {rank = 15, phase = 1, value = 255},
    ["Gavel of Pure Light"] = {rank = 16, phase = 1, value = 255},
    ["Hammer of the Penitent"] = {rank = 17, phase = 1, value = 222.4},
    ["Hammer of the Twisting Nether"] = {rank = 18, phase = 0, value = 219.6},
    ["Dathrohan's Ceremonial Hammer"] = {rank = 19, phase = 1, value = 211.45},
    ["Lightsworn Hammer"] = {rank = 20, phase = 1, value = 211},
    ["The Essence Focuser"] = {rank = 21, phase = 1, value = 209.1},
    ["Runed Dagger of Solace"] = {rank = 22, phase = 1, value = 182.8},
    ["Will of the Fallen Exarch"] = {rank = 23, phase = 1, value = 182.55},
    ["Ceremonial Kris"] = {rank = 24, phase = 1, value = 181.7},
    ["Mogor's Anointing Club"] = {rank = 25, phase = 1, value = 151.85},
    ["Azure Lightblade"] = {rank = 26, phase = 1, value = 137.7},
    -- Two Hand
    ["Golden Staff of the Sin'dorei"] = {rank = 1, phase = 5, value = 624.4},
    ["Apostle of Argus"] = {rank = 2, phase = 3, value = 496.6},
    ["Staff of Immaculate Recovery"] = {rank = 3, phase = 3, value = 468.85},
    ["Staff of Dark Mending"] = {rank = 4, phase = 4, value = 448.9},
    ["Exodar Life-Staff"] = {rank = 5, phase = 1, value = 433.4},
    ["Ethereum Life-Staff"] = {rank = 6, phase = 2, value = 431.8},
    ["Atiesh, Greatstaff of the Guardian"] = {rank = 7, phase = 0, value = 414.8},
    ["Crystalheart Pulse-Staff"] = {rank = 8, phase = 1, value = 388.15},
    ["Nightstaff of the Everliving"] = {rank = 9, phase = 1, value = 362.25},
    ["Serpentcrest Life-Staff"] = {rank = 10, phase = 1, value = 250.55},
    ["Seer's Cane"] = {rank = 11, phase = 1, value = 245.6},
    ["Epoch-Mender"] = {rank = 12, phase = 1, value = 239.85},
    ["Staff of Divine Infusion"] = {rank = 13, phase = 1, value = 223.6},
    ["Ameer's Judgement"] = {rank = 14, phase = 1, value = 219.86},
    ["Staff of the Ashtongue Deathsworn"] = {rank = 15, phase = 1, value = 217.55},
    ["Staff of the Redeemer"] = {rank = 16, phase = 1, value = 217.55},
    ["Ironstaff of Regeneration"] = {rank = 17, phase = 1, value = 174.25},
    -- Off Hand
    ["Book of Highborne Hymns"] = {rank = 1, phase = 5, value = 122.55},
    ["Scepter of Purification"] = {rank = 2, phase = 3, value = 101.4},
    ["Voodoo Shaker"] = {rank = 3, phase = 4, value = 85.9},
    ["Talisman of the Sun King"] = {rank = 4, phase = 2, value = 82.75},
    ["Aran's Soothing Sapphire"] = {rank = 5, phase = 1, value = 78.4},
    ["Windcaller's Orb"] = {rank = 6, phase = 1, value = 72.6},
    ["Signet of Unshakable Faith"] = {rank = 7, phase = 1, value = 69.35},
    ["Tears of Heaven"] = {rank = 8, phase = 1, value = 68.5},
    ["Sapphiron's Right Eye"] = {rank = 9, phase = 0, value = 68.05},
    ["Faol's Signet of Cleansing"] = {rank = 10, phase = 1, value = 64.7},
    ["Swamplight Lantern"] = {rank = 11, phase = 1, value = 64.6},
    ["Lordaeron Medical Guide"] = {rank = 12, phase = 1, value = 61.4},
    ["Sartura's Might"] = {rank = 13, phase = 0, value = 58.4},
    ["Lamp of Peaceful Repose"] = {rank = 14, phase = 1, value = 58.2},
    ["Uneathed Orb"] = {rank = 15, phase = 1, value = 46.1},
    -- Wands
    ["Wand of Cleansing Light"] = {rank = 1, phase = 5, value = 84},
    ["Luminescent Rod of the Naaru"] = {rank = 2, phase = 2, value = 54.2},
    ["Blue Diamond Witchwand"] = {rank = 3, phase = 1, value = 44.6},
    ["Carved Witch Doctor's Stick"] = {rank = 4, phase = 4, value = 39.05},
    ["Wand of the Whispering Dead"] = {rank = 5, phase = 0, value = 34.6},
    ["Soul-Wand of the Aldor"] = {rank = 6, phase = 1, value = 34.45},
    ["Calming Spore Reed"] = {rank = 7, phase = 1, value = 31.4},
    ["Rejuvenating Scepter"] = {rank = 8, phase = 1, value = 29.8},
    ["Illidari Rod of Discipline"] = {rank = 9, phase = 1, value = 24.65},
    ["Wand of Happiness"] = {rank = 10, phase = 1, value = 21.3},
    ["Ogre Handler's Shooter"] = {rank = 11, phase = 1, value = 21.3},
    ["Antenna of Invigoration"] = {rank = 12, phase = 0, value = 21.1},
    ["Wand of the Ancestors"] = {rank = 13, phase = 1, value = 16},
    ["Arcane Wand of Sylvanaar"] = {rank = 14, phase = 1, value = 16},
    -- Gems
    -- Red
    ["Teardrop Crimson Spinel"] = {rank = 1, phase = 3, value = 17.6},
    ["Teardrop Living Ruby"] = {rank = 2, phase = 1, value = 14.4},
    -- Purple
    ["Royal Tanzanite"] = {rank = 1, phase = 1, value = 13.8},
    ["Purified Shadowsong Amethyst"] = {rank = 2, phase = 5, value = 13.8},
    ["Royal Shadowsong Amethyst"] = {rank = 3, phase = 3, value = 13.8},
    ["Imperial Tanzanite"] = {rank = 4, phase = 1, value = 12.2},
    ["Royal Nightseye"] = {rank = 5, phase = 1, value = 12.2},
    ["Purified Shadow Pearl"] = {rank = 6, phase = 1, value = 11.2},
    ["Blessed Tanzanite"] = {rank = 7, phase = 1, value = 9.1},
    ["Soothing Amethyst"] = {rank = 8, phase = 1, value = 9.1},
    -- Blue
    ["Lustrous Empyrean Sapphire"] = {rank = 1, phase = 3, value = 10},
    ["Sparkling Empyrean Sapphire"] = {rank = 2, phase = 3, value = 10},
    ["Sparkling Star of Elune"] = {rank = 3, phase = 1, value = 8},
    ["Lustrous Star of Elune"] = {rank = 4, phase = 1, value = 7.5},
    ["Solid Empyrean Sapphire"] = {rank = 5, phase = 3, value = 0.75},
    ["Solid Star of Elune"] = {rank = 6, phase = 1, value = 0.6},
    -- Green
    ["Dazzling Chrysoprase"] = {rank = 1, phase = 1, value = 9},
    ["Dazzling Seaspray Emerald"] = {rank = 2, phase = 3, value = 9},
    ["Seer's Chrysoprase"] = {rank = 3, phase = 1, value = 8.2},
    ["Dazzling Talasite"] = {rank = 4, phase = 1, value = 8.2},
    -- Yellow
    ["Quick Lionseye"] = {rank = 1, phase = 3, value = 12},
    ["Quick Dawnstone"] = {rank = 2, phase = 1, value = 9.6},
    ["Brilliant Lionseye"] = {rank = 3, phase = 3, value = 8},
    ["Brilliant Dawnstone"] = {rank = 4, phase = 1, value = 6.4},
    ["Mystic Lionseye"] = {rank = 5, phase = 3, value = 0},
    ["Mystic Dawnstone"] = {rank = 6, phase = 1, value = 0},
    -- Orange
    ["Luminous Pyrestone"] = {rank = 1, phase = 3, value = 12.8},
    ["Luminous Fire Opal"] = {rank = 2, phase = 1, value = 12},
    ["Reckless Pyrestone"] = {rank = 3, phase = 3, value = 10.8},
    ["Luminous Noble Topaz"] = {rank = 4, phase = 1, value = 10.4},
    ["Reckless Noble Topaz"] = {rank = 5, phase = 1, value = 8.8},
    -- Meta
    ["Insightful Earthstorm Diamond"] = {rank = 1, phase = 1, value = 40.6}
}
