items = {
    -- Head
    ["Circlet of Faith"] = "R: 1, S: 169, P 6",
    ["Don Rigoberto's Lost Hat"] = "R: 2, S: 149, P 5",
    ["Crystal Adorned Crown"] = "R: 3, S:130, P: 2",
    ["Tiara of the Oracle"] = "R: 4, S: 121, P: 5",
    ["Halo of Transcendence"] = "R: 5, S: 120, P: 1",
    ["Virtuous Crown"] = "R: 6, S: 100, P: 5",
    ["Dustwind Turban"] = "R: 7, S: 99, P: 5",
    ["Zulian Headdress"] = "R: 8, S: 99, P:4",
    ["Mish'undare, Circlet of the Mind Flayer"] = "R: 9, S: 93, P: 3",
    ["Field Marshal's Headdress"] = "R: 10, S: 88, P: 2",
    ["Warlord's Satin Cowl"] = "R: 10, S: 88, P: 2",
    -- Neck
    ["Amulet of the Fallen God"] = "R: 1, S: 90, P: 5",
    ["Pendant of Forgotten Names"] = "R: 2, S: 88, P: 6",
    ["Necklace of Necropsy"] = "R: 3, S: 85, P: 6",
    ["Angelista's Charm"] = "R: 4, S: 79, P: 5",
    ["Amulet of the Shifting Sands"] = "R: 5, S: 77, P: 5",
    ["Wavefront Necklace"] = "R: 6, S: 72, P: 4",
    ["Jin'do's Evil Eye"] = "R: 7, S: 67, P: 4",
    ["Pendant of the Fallen Dragon"] = "R: 8, S: 61, P: 3",
    ["The All-Seeing Eye of Zuldazar"] = "R: 9, S: 52, P: 4",
    ["Choker of Enlightenment"] = "R: 10, S: 48, P: 1",
    ["Animated Chain Necklace"] = "R: 11, S: 45, P: 1",
    -- Shoulders
    ["Shoulderpads of Faith"] = "R: 1, S: 120, P: 6",
    ["Ternary Mantle"] = "R: 2, S: 101, P: 5",
    ["Pauldrons of Transcendence"] = "R: 3, S: 78, P: 3",
    ["Zandalar Confessor's Mantle"] = "R: 4, S: 77, P: 4",
    ["Mantle of the Oracle"] = "R: 5, S: 75, P: 5",
    ["Champion's Satin Mantle"] = "R: 6, S: 62, P: 2",
    ["Lieutenant Commander's Satin Mantle"] = "R: 6, S: 62, P: 2",
    ["Rime Covered Mantle"] = "R: 7, S: 60, P: 6",
    ["Abyssal Cloth Amice of Restoration"] = "R: 8, S: 57, P: 4",
    ["Mantle of the Scarlet Crusade"] = "R: 9, S: 56, P: 5",
    ["Mantle of Prophecy"] = "R: 10, S: 54, P: 1",
    -- Back
    ["Cloak of Suturing"] = "R: 1, S: 109, P: 6",
    ["Cloak of Clarity"] = "R: 2, S: 108, P: 5",
    ["Shroud of Pure Thought"] = "R: 3, S: 77, P: 3",
    ["Drape of Benediction"] = "R: 4, S: 61, P: 2",
    ["Shroud of Infinite Wisdom"] = "R: 5, S: 61, P: 5",
    ["Hakkari Loa Cloak"] = "R: 6, S: 55, P: 4",
    ["Cloak of the Savior"] = "R: 7, S: 54, P: 5",
    ["Hide of the Wild"] = "R: 8, S: 53, P: 2",
    ["Archivist Cape of Healing"] = "R: 9, S: 53, P: 1",
    ["Archivist Cape of The Owl"] = "R: 10, S: 49, P: 1",
    -- Chest
    ["Robe of Faith"] = "R: 1, S: 162, P: 6",
    ["Robes of the Guardian Saint"] = "R: 2, S: 133, P: 5",
    ["Robes of Transcendence"] = "R: 3, S: 118, P: 3",
    ["Truefaith Vestments"] = "R: 4, S: 107, P: 1",
    ["Vestments of the Oracle"] = "R: 5, S: 102, P: 5",
    ["Virtuous Robe"] = "R: 6, S: 94, P: 5",
    ["Flowing Ritual Robes"] = "R: 7, S: 93, P: 4",
    ["Robes of the Exalted"] = "R: 8, S: 93, P: 1",
    ["Field Marshal's Satin Vestments"] = "R: 9, S: 88, P: 2",
    ["Warlord's Satin Robes"] = "R: 9, S: 88, P: 2",
    ["Robes of Prophecy"] = "R: 10, S: 85, P: 1",
    -- Wrist
    ["Bindings of Faith"] = "R: 1, S: 89, P: 6",
    ["Bracers of Royal Redemption"] = "R: 2, S: 81, P: 5",
    ["Bindings of Transcendence"] = "R: 3, S: 78, P: 3",
    ["Vambraces of Prophecy"] = "R: 4, S: 69, P: 1",
    ["Zandalar Confessor's Wraps"] = "R: 5, S: 59, P: 4",
    ["Flarecore Wraps"] = "R: 6, S: 55, P: 1",
    ["Bracers of Hope"] = "R: 7, S: 53, P: 6",
    ["Bracers of Mending"] = "R: 8, S: 52, P: 6",
    ["Avyssal Cloth Wristbands of Restoration"] = "R: 9, S: 49, P: 4",
    ["Dryad's Wrist Bindings"] = "R: 10, S: 45, P: 3",
    -- Hands
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",
    [""] = "R: , S: , P: ",

    



}